name: Deploy to github pages
on:
    push:
        branches:
            - production  
    pull_request:
        branches:
            - production
permissions:
    contents: read
    pages: write
    id-token: write
jobs:
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deploy-to-github-pages.outputs.url }}
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./frontend
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                version: latest
            - name: Setup Node-js environment
              uses: actions/setup-node@v3
              with:
                node-version: 18.x
                cache: pnpm
                cache-dependency-path: ./frontend/pnpm-lock.yaml
            - name: Install dependencies
              run: pnpm install
            - name: Build
              run: pnpm run build
            - name: Setup pages
              uses: actions/configure-pages@v3
            - name: Upload pages
              uses: actions/upload-artifact@v2
              with:
                path: ./frontend/build
            - name: Deploy to github pages
              id:   deploy-to-github-pages
              uses: actions/deploy-pages@v1